% input parameters for outdoors/bricks_*.MP4

expname = 'outdoors';
calname = 'concrete_calibration';
vidtype = '.MP4';
input_type = 'video';
names = {...
    'concrete_one_person_walking_circles',...
    'concrete_one_person_walking_randomly',...
    'concrete_two_people_walking_randomly'...
    };
